- maven/org.eclipse.emf.mwe2.parent/pom.xml
> [#5] update to tycho 1.2.0

- plugins/org.eclipse.emf.mwe.activities/META-INF/MANIFEST.MF
- plugins/org.eclipse.emf.mwe.core/META-INF/MANIFEST.MF
- plugins/org.eclipse.emf.mwe.ui.simpleEditor/META-INF/MANIFEST.MF
- plugins/org.eclipse.emf.mwe.ui/META-INF/MANIFEST.MF
- plugins/org.eclipse.emf.mwe.utils/META-INF/MANIFEST.MF
- plugins/org.eclipse.emf.mwe2.language.ui/META-INF/MANIFEST.MF
- plugins/org.eclipse.emf.mwe2.language/META-INF/MANIFEST.MF
- plugins/org.eclipse.emf.mwe2.launch.ui/META-INF/MANIFEST.MF
- plugins/org.eclipse.emf.mwe2.launch/META-INF/MANIFEST.MF
- plugins/org.eclipse.emf.mwe2.lib/META-INF/MANIFEST.MF
- plugins/org.eclipse.emf.mwe2.runtime/META-INF/MANIFEST.MF
- tests/org.eclipse.emf.mwe.tests/META-INF/MANIFEST.MF
- tests/org.eclipse.emf.mwe2.language.tests/META-INF/MANIFEST.MF
[#8] added Automatic-Module-Name Headers
> [#8] added Automatic-Module-Name Headers

- maven/org.eclipse.emf.mwe2.target/org.eclipse.emf.mwe2.target.target
- plugins/org.eclipse.emf.mwe2.language/model/Mwe2.ecore
- plugins/org.eclipse.emf.mwe2.language/model/Mwe2.genmodel
> regenerated metamodel files

- plugins/org.eclipse.emf.mwe2.language/src/org/eclipse/emf/mwe2/language/serializer/Mwe2SemanticSequencer.java
> adapted to new sequencer api

- maven/.mvn/extensions.xml
> use tycho 1.2.0 for pomless

- plugins/org.eclipse.emf.mwe.core/src/org/eclipse/emf/mwe/core/resources/AbstractResourceLoader.java
- plugins/org.eclipse.emf.mwe.ui/src/org/eclipse/emf/mwe/internal/ui/eclipse/launch/MWELaunchShortcut.java
- plugins/org.eclipse.emf.mwe.ui/src/org/eclipse/emf/mwe/ui/workflow/util/ProjectIncludingResourceLoader.java
- plugins/org.eclipse.emf.mwe.utils/src/org/eclipse/emf/mwe/utils/FileCopy.java
- plugins/org.eclipse.emf.mwe.utils/src/org/eclipse/emf/mwe/utils/GenModelHelper.java
- plugins/org.eclipse.emf.mwe.utils/src/org/eclipse/emf/mwe/utils/StandaloneSetup.java
- plugins/org.eclipse.emf.mwe2.language.ui/src/org/eclipse/emf/mwe2/language/ui/Mwe2UiModule.java
- plugins/org.eclipse.emf.mwe2.language.ui/src/org/eclipse/emf/mwe2/language/ui/highlighting/SemanticHighlightingCalculator.java
- tests/org.eclipse.emf.mwe.tests/src/org/eclipse/emf/mwe/tests/util/StandaloneSetupTest.java
> fixed deprecated code

- releng/MWE.setup
One working set exclusion rule got broken due to manual editing.
Also added EMF latest to target platform (eclipse/mwe#39)
Change-Id: Id1a9494ac89160f3241d3f74d699ee3b22780750
Signed-off-by: Karsten Thoms <karsten.thoms@itemis.de>
> [540359] Fixed broken reference to working set

- releng/MWE.setup
[540359] fixed broken github link
> [540359] fixed broken github link

- releng/MWE.setup
> added complete jdt to target platform

- features/org.eclipse.emf.mwe2.language.sdk-feature/feature.xml
> fixed wrong minimal xtext version

- maven/org.eclipse.emf.mwe2.target/org.eclipse.emf.mwe2.target.target
> use specific version of license feature

- releng/MWE.setup
> added to cbi repo list

- plugins/org.eclipse.emf.mwe2.launch.ui/src/org/eclipse/emf/mwe2/launch/ui/shortcut/Mwe2LaunchShortcut.java
[#57] support for source folder separation for tests
> [#57] support for source folder separation for tests

- maven/.mvn/extensions.xml
> switch to tycho 1.3

- maven/org.eclipse.emf.mwe2.parent/pom.xml
- plugins/org.eclipse.emf.mwe.core/src-ant/org/eclipse/emf/mwe/core/ant/WorkflowAntTask.java
- plugins/org.eclipse.emf.mwe.core/src/org/eclipse/emf/mwe/core/WorkflowComponent.java
- plugins/org.eclipse.emf.mwe.core/src/org/eclipse/emf/mwe/core/WorkflowEngine.java
- plugins/org.eclipse.emf.mwe.core/src/org/eclipse/emf/mwe/core/WorkflowRunner.java
- plugins/org.eclipse.emf.mwe.core/src/org/eclipse/emf/mwe/core/ao/AbstractWorkflowAdvice.java
- plugins/org.eclipse.emf.mwe.core/src/org/eclipse/emf/mwe/core/container/CompositeComponent.java
- plugins/org.eclipse.emf.mwe.core/src/org/eclipse/emf/mwe/core/debug/processing/ElementAdapter.java
- plugins/org.eclipse.emf.mwe.core/src/org/eclipse/emf/mwe/core/issues/Issues.java
- plugins/org.eclipse.emf.mwe.core/src/org/eclipse/emf/mwe/core/monitor/ProgressMonitorAdapter.java
- plugins/org.eclipse.emf.mwe.core/src/org/eclipse/emf/mwe/internal/core/debug/mwe/ReflectionUtil.java
- plugins/org.eclipse.emf.mwe.core/src/org/eclipse/emf/mwe/internal/core/debug/processing/ProcessHandler.java
- plugins/org.eclipse.emf.mwe.core/src/org/eclipse/emf/mwe/internal/core/debug/processing/handlers/CommandRuntimeHandler.java
- plugins/org.eclipse.emf.mwe.core/src/org/eclipse/emf/mwe/internal/core/debug/processing/handlers/EventRuntimeHandler.java
- plugins/org.eclipse.emf.mwe.core/src/org/eclipse/emf/mwe/internal/core/debug/processing/handlers/VariablesRuntimeHandler.java
- plugins/org.eclipse.emf.mwe2.language/src/org/eclipse/emf/mwe2/language/formatting/Mwe2Formatter.java
> fixed tons of broken javadocs

- features/org.eclipse.emf.mwe2.language.sdk-feature/feature.properties
- features/org.eclipse.emf.mwe2.launcher-feature/feature.properties
- features/org.eclipse.emf.mwe2.runtime.sdk-feature/feature.properties
- plugins/org.eclipse.emf.mwe2.language.ide/META-INF/MANIFEST.MF
- plugins/org.eclipse.emf.mwe2.language.ui/plugin.properties
- plugins/org.eclipse.emf.mwe2.language/META-INF/MANIFEST.MF
- plugins/org.eclipse.emf.mwe2.launch.ui/plugin.properties
- plugins/org.eclipse.emf.mwe2.launch/plugin.properties
- plugins/org.eclipse.emf.mwe2.lib/META-INF/MANIFEST.MF
- plugins/org.eclipse.emf.mwe2.runtime/META-INF/MANIFEST.MF
- tests/org.eclipse.emf.mwe2.language.tests/META-INF/MANIFEST.MF
> [#64] Streamline feature & plugin names

- maven/org.eclipse.emf.mwe2.parent/pom.xml
> update to tycho 1.4.0

- releng/MWE.setup
Change-Id: I42a02a90920bdbc0677ea41435121c2464c85f4f
Signed-off-by: Karsten Thoms <karsten.thoms@itemis.de>
> Fix broken link in excludedWorkingSet configuration

- maven/org.eclipse.emf.mwe2.repository/category.xml
- maven/org.eclipse.emf.mwe2.target/org.eclipse.emf.mwe2.latest-target.target
- maven/org.eclipse.emf.mwe2.target/org.eclipse.emf.mwe2.target.target
> package guava 27.1 to mwe update site

- releng/MWE.setup
added support for 2019-03 in tp
> added support for 2019-03 in tp

- features/pom.xml
- plugins/pom.xml
removed duplicate plugin versions
> removed duplicate plugin versions

- releng/MWE.setup
> offer 2019-09 in oomph

- Jenkinsfile
> [#103] fixed deploy vs verify

- maven/org.eclipse.emf.mwe2.target/org.eclipse.emf.mwe2.latest-target.target
- maven/org.eclipse.emf.mwe2.target/org.eclipse.emf.mwe2.target.target
> use orbit 2019-12

- Jenkinsfile
> [#104] disabled junitPublisher in withMaven

- releng/MWE.setup
> added 2019-12 to mwe setup

- maven/org.eclipse.emf.mwe2.parent/pom.xml
[#110] reintroduced proper default for sign.skip
> [#110] reintroduced proper default for sign.skip

- maven/org.eclipse.emf.mwe2.parent/pom.xml
> update to tycho 1.5.1

- tests/org.eclipse.emf.mwe2.language.tests/src/org/eclipse/emf/mwe2/language/tests/validation/Mwe2ValidatorTest.java
Signed-off-by: Tamas Miklossy <miklossy@itemis.de>
> Refactoring the Mwe2ValidatorTest to use the Xtext ValidationTestHelper.

- tests/org.eclipse.emf.mwe2.language.tests/src/org/eclipse/emf/mwe2/language/tests/validation/Mwe2ValidatorTest.java
Signed-off-by: Tamas Miklossy <miklossy@itemis.de>
> Improve Exception handling in the Mwe2ValidatorTest class.

- Jenkinsfile
When building a release old milestone update sites are deleted and the
composite site descriptor for the milestones is re-created. The last 3
milestones are kept.
On every build old nightly and milestone drops are deleted from the
download area. Here it must be considered that directories are located
in a nested structure and that sorting by paths is not sufficient. This
would make a '2.9' version appear younger than a '2.1x' version.
Change-Id: I1b7b0fe4cf1fdfd8ec6267d555e522db97ab9900
Signed-off-by: Karsten Thoms <karsten.thoms@itemis.de>
> Cleanup actions for old nightlies and milestones

- Jenkinsfile
[#132] fixed broken nightly deployment
> [#132] fixed broken nightly deployment

- README.md
Signed-off-by: Nico Prediger <mail@nicoprediger.de>
> add release documentation to README.me

- plugins/org.eclipse.emf.mwe2.language.ide/src-gen/org/eclipse/emf/mwe2/language/ide/AbstractMwe2IdeModule.java
- plugins/org.eclipse.emf.mwe2.language.ide/src-gen/org/eclipse/emf/mwe2/language/ide/contentassist/Mwe2ContentAssistLexer.java
- plugins/org.eclipse.emf.mwe2.language.ide/src-gen/org/eclipse/emf/mwe2/language/ui/highlighting/MweHighlightingLexer.java
- plugins/org.eclipse.emf.mwe2.language.ui/META-INF/MANIFEST.MF
- plugins/org.eclipse.emf.mwe2.language.ui/src-gen/org/eclipse/emf/mwe2/language/ui/AbstractMwe2UiModule.java
- plugins/org.eclipse.emf.mwe2.language/build.properties
- plugins/org.eclipse.emf.mwe2.language/generator/org/eclipse/emf/mwe2/language/GenerateMwe2.java
- plugins/org.eclipse.emf.mwe2.language/src-gen/org/eclipse/emf/mwe2/language/AbstractMwe2RuntimeModule.java
- plugins/org.eclipse.emf.mwe2.language/src-gen/org/eclipse/emf/mwe2/language/lexer/Mwe2Lexer.java
[#116] update to external lexer in new generator
> [#116] update to external lexer in new generator

- maven/org.eclipse.emf.mwe2.parent/pom.xml
> update to tycho 1.6.0

- NOTICE.md
> added NOTICE.md

- README.md
[eclipse/mwe#147] Add note to provide git tag
> [eclipse/mwe#147] Add note to provide git tag

- maven/org.eclipse.emf.mwe2.parent/pom.xml
- maven/org.eclipse.emf.mwe2.target/org.eclipse.emf.mwe2.latest-target.target
- maven/org.eclipse.emf.mwe2.target/org.eclipse.emf.mwe2.target.target
Tycho 1.7 & harmonize IncludeSource
> Tycho 1.7 & harmonize IncludeSource

- plugins/org.eclipse.emf.mwe.core/src/org/eclipse/emf/mwe/core/WorkflowRunner.java
- plugins/org.eclipse.emf.mwe.core/src/org/eclipse/emf/mwe/core/resources/ResourceLoaderFactory.java
- plugins/org.eclipse.emf.mwe.core/src/org/eclipse/emf/mwe/internal/core/debug/processing/RuntimeHandlerManager.java
- plugins/org.eclipse.emf.mwe.utils/src/org/eclipse/emf/mwe/utils/StandaloneSetup.java
- plugins/org.eclipse.emf.mwe2.language/src/org/eclipse/emf/mwe2/language/factory/Mwe2ExecutionEngine.java
- plugins/org.eclipse.emf.mwe2.launch/src/org/eclipse/emf/mwe2/launch/runtime/Mwe2Runner.java
- tests/org.eclipse.emf.mwe.tests/resources/test/res/Component.java
fixed Java 11 warnings
DO not merge before Xtext 2.23 is released
> fixed Java 11 warnings

- plugins/org.eclipse.emf.mwe2.lib/src/org/eclipse/emf/mwe2/ecore/EcoreGenerator.java
Suggested solution for [Bug 567752](https://bugs.eclipse.org/bugs/show_bug.cgi?id=567752).
> [567752] Add model code generation flag.

- plugins/org.eclipse.emf.mwe2.lib/src/org/eclipse/emf/mwe2/ecore/EcoreGenerator.java
Version 2.11.4 was abandoned and replaced by 2.12.0
Change-Id: I07360c3c523efa414ed70d3f7b4a71abb71bac4d
Signed-off-by: Karsten Thoms <karsten.thoms@karakun.com>
> Bug 567752 - Update since version to 2.12

- plugins/org.eclipse.emf.mwe.utils/src/org/eclipse/emf/mwe/utils/Writer.java
Bumped MWE version to 1.6 since this adds API
> Writer: Make encoding configurable

- documentation/mwe2.md
> enhanced docs

- plugins/org.eclipse.emf.mwe2.language.ui/src/org/eclipse/emf/mwe2/language/ui/quickfix/Mwe2QuickfixProvider.java
[#156] Add quickfix to remove unused variables
Fixes #156
> [#156] Add quickfix to remove unused variables

- features/org.eclipse.emf.mwe2.launcher-feature/feature.xml
- features/org.eclipse.emf.mwe2.runtime.sdk-feature/feature.xml
- maven/org.eclipse.emf.mwe2.parent/pom.xml
- maven/org.eclipse.emf.mwe2.repository/category.xml
- maven/org.eclipse.emf.mwe2.target/org.eclipse.emf.mwe2.target.target
- plugins/org.eclipse.emf.mwe2.language.ui/META-INF/MANIFEST.MF
- plugins/org.eclipse.emf.mwe2.language/META-INF/MANIFEST.MF
- plugins/org.eclipse.emf.mwe2.lib/META-INF/MANIFEST.MF
- releng/MWE.setup
Signed-off-by: miklossy <miklossy@itemis.de>
> [#177] Update Google Guava version from 27.1.0 to 30.1.0

- plugins/org.eclipse.emf.mwe2.language.ide/src-gen/org/eclipse/emf/mwe2/language/ide/AbstractMwe2IdeModule.java
- plugins/org.eclipse.emf.mwe2.language.ide/src-gen/org/eclipse/emf/mwe2/language/ide/contentassist/antlr/Mwe2Parser.java
- plugins/org.eclipse.emf.mwe2.language.ide/src-gen/org/eclipse/emf/mwe2/language/ide/contentassist/antlr/PartialMwe2ContentAssistParser.java
- plugins/org.eclipse.emf.mwe2.language.ide/src-gen/org/eclipse/emf/mwe2/language/ide/contentassist/antlr/internal/InternalMwe2Parser.g
- plugins/org.eclipse.emf.mwe2.language.ide/src-gen/org/eclipse/emf/mwe2/language/ide/contentassist/antlr/internal/InternalMwe2Parser.java
- plugins/org.eclipse.emf.mwe2.language.ide/src-gen/org/eclipse/emf/mwe2/language/ide/contentassist/antlr/lexer/InternalMwe2Lexer.g
- plugins/org.eclipse.emf.mwe2.language.ide/src-gen/org/eclipse/emf/mwe2/language/ide/contentassist/antlr/lexer/InternalMwe2Lexer.java
- plugins/org.eclipse.emf.mwe2.language.ui/plugin.xml_gen
- plugins/org.eclipse.emf.mwe2.language.ui/src-gen/org/eclipse/emf/mwe2/language/ui/AbstractMwe2UiModule.java
- plugins/org.eclipse.emf.mwe2.language.ui/src-gen/org/eclipse/emf/mwe2/language/ui/Mwe2ExecutableExtensionFactory.java
- plugins/org.eclipse.emf.mwe2.language.ui/src-gen/org/eclipse/emf/mwe2/language/ui/contentassist/AbstractMwe2ProposalProvider.java
- plugins/org.eclipse.emf.mwe2.language.ui/src-gen/org/eclipse/emf/mwe2/language/ui/internal/LanguageActivator.java
- plugins/org.eclipse.emf.mwe2.language/src-gen/org/eclipse/emf/mwe2/language/AbstractMwe2RuntimeModule.java
- plugins/org.eclipse.emf.mwe2.language/src-gen/org/eclipse/emf/mwe2/language/Mwe2StandaloneSetupGenerated.java
- plugins/org.eclipse.emf.mwe2.language/src-gen/org/eclipse/emf/mwe2/language/parser/antlr/Mwe2AntlrTokenFileProvider.java
- plugins/org.eclipse.emf.mwe2.language/src-gen/org/eclipse/emf/mwe2/language/parser/antlr/Mwe2Parser.java
- plugins/org.eclipse.emf.mwe2.language/src-gen/org/eclipse/emf/mwe2/language/parser/antlr/internal/InternalMwe2Parser.g
- plugins/org.eclipse.emf.mwe2.language/src-gen/org/eclipse/emf/mwe2/language/parser/antlr/internal/InternalMwe2Parser.java
- plugins/org.eclipse.emf.mwe2.language/src-gen/org/eclipse/emf/mwe2/language/parser/antlr/lexer/InternalMwe2Lexer.g
- plugins/org.eclipse.emf.mwe2.language/src-gen/org/eclipse/emf/mwe2/language/parser/antlr/lexer/InternalMwe2Lexer.java
- plugins/org.eclipse.emf.mwe2.language/src-gen/org/eclipse/emf/mwe2/language/scoping/AbstractMwe2ScopeProvider.java
- plugins/org.eclipse.emf.mwe2.language/src-gen/org/eclipse/emf/mwe2/language/serializer/AbstractMwe2SemanticSequencer.java
- plugins/org.eclipse.emf.mwe2.language/src-gen/org/eclipse/emf/mwe2/language/serializer/AbstractMwe2SyntacticSequencer.java
- plugins/org.eclipse.emf.mwe2.language/src-gen/org/eclipse/emf/mwe2/language/services/Mwe2GrammarAccess.java
- plugins/org.eclipse.emf.mwe2.language/src-gen/org/eclipse/emf/mwe2/language/validation/AbstractMwe2Validator.java
> regenerated with Xtext 2.25

- plugins/org.eclipse.emf.mwe2.language.ui/plugin.xml
> Align formatting of plugin.xml to plugin.xml_gen

- maven/org.eclipse.emf.mwe2.target/org.eclipse.emf.mwe2.target.target
Updated target platform to Xtext 2.25.0 release
Fixes #186
> Updated target platform to Xtext 2.25.0 release

- maven/org.eclipse.emf.mwe2.parent/pom.xml
[#190] use newest cbi plugin to use new signing service url
> [#190] use newest cbi plugin to use new signing service url

- tests/org.eclipse.emf.mwe.tests/pom.xml
> use latest junit 4

- Jenkinsfile
- features/org.eclipse.emf.mwe2.language.sdk-feature/feature.xml
- features/org.eclipse.emf.mwe2.launcher-feature/feature.xml
- features/org.eclipse.emf.mwe2.runtime.sdk-feature/feature.xml
- maven/org.eclipse.emf.mwe2.parent/pom.xml
- maven/org.eclipse.emf.mwe2.target/org.eclipse.emf.mwe2.target.target
- plugins/org.eclipse.emf.mwe2.language/META-INF/MANIFEST.MF
- plugins/org.eclipse.emf.mwe2.runtime/META-INF/MANIFEST.MF
- tests/org.eclipse.emf.mwe2.language.tests/META-INF/MANIFEST.MF
> update to guice 5

- Jenkinsfile
> switch to termurin

- maven/org.eclipse.emf.mwe2.target/org.eclipse.emf.mwe2.target.target
> update to orbit 2021-12

- plugins/org.eclipse.emf.mwe2.language.ide/src-gen/org/eclipse/emf/mwe2/language/ide/AbstractMwe2IdeModule.java
- plugins/org.eclipse.emf.mwe2.language.ide/src-gen/org/eclipse/emf/mwe2/language/ide/contentassist/antlr/Mwe2Parser.java
- plugins/org.eclipse.emf.mwe2.language.ide/src-gen/org/eclipse/emf/mwe2/language/ide/contentassist/antlr/PartialMwe2ContentAssistParser.java
- plugins/org.eclipse.emf.mwe2.language.ide/src-gen/org/eclipse/emf/mwe2/language/ide/contentassist/antlr/internal/InternalMwe2Parser.g
- plugins/org.eclipse.emf.mwe2.language.ide/src-gen/org/eclipse/emf/mwe2/language/ide/contentassist/antlr/internal/InternalMwe2Parser.java
- plugins/org.eclipse.emf.mwe2.language.ide/src-gen/org/eclipse/emf/mwe2/language/ide/contentassist/antlr/lexer/InternalMwe2Lexer.g
- plugins/org.eclipse.emf.mwe2.language.ide/src-gen/org/eclipse/emf/mwe2/language/ide/contentassist/antlr/lexer/InternalMwe2Lexer.java
- plugins/org.eclipse.emf.mwe2.language.ui/src-gen/org/eclipse/emf/mwe2/language/ui/AbstractMwe2UiModule.java
- plugins/org.eclipse.emf.mwe2.language.ui/src-gen/org/eclipse/emf/mwe2/language/ui/Mwe2ExecutableExtensionFactory.java
- plugins/org.eclipse.emf.mwe2.language.ui/src-gen/org/eclipse/emf/mwe2/language/ui/contentassist/AbstractMwe2ProposalProvider.java
- plugins/org.eclipse.emf.mwe2.language.ui/src-gen/org/eclipse/emf/mwe2/language/ui/internal/LanguageActivator.java
- plugins/org.eclipse.emf.mwe2.language/src-gen/org/eclipse/emf/mwe2/language/AbstractMwe2RuntimeModule.java
- plugins/org.eclipse.emf.mwe2.language/src-gen/org/eclipse/emf/mwe2/language/Mwe2StandaloneSetupGenerated.java
- plugins/org.eclipse.emf.mwe2.language/src-gen/org/eclipse/emf/mwe2/language/parser/antlr/Mwe2AntlrTokenFileProvider.java
- plugins/org.eclipse.emf.mwe2.language/src-gen/org/eclipse/emf/mwe2/language/parser/antlr/Mwe2Parser.java
- plugins/org.eclipse.emf.mwe2.language/src-gen/org/eclipse/emf/mwe2/language/parser/antlr/internal/InternalMwe2Parser.g
- plugins/org.eclipse.emf.mwe2.language/src-gen/org/eclipse/emf/mwe2/language/parser/antlr/internal/InternalMwe2Parser.java
- plugins/org.eclipse.emf.mwe2.language/src-gen/org/eclipse/emf/mwe2/language/parser/antlr/lexer/InternalMwe2Lexer.g
- plugins/org.eclipse.emf.mwe2.language/src-gen/org/eclipse/emf/mwe2/language/parser/antlr/lexer/InternalMwe2Lexer.java
- plugins/org.eclipse.emf.mwe2.language/src-gen/org/eclipse/emf/mwe2/language/scoping/AbstractMwe2ScopeProvider.java
- plugins/org.eclipse.emf.mwe2.language/src-gen/org/eclipse/emf/mwe2/language/serializer/AbstractMwe2SemanticSequencer.java
- plugins/org.eclipse.emf.mwe2.language/src-gen/org/eclipse/emf/mwe2/language/serializer/AbstractMwe2SyntacticSequencer.java
- plugins/org.eclipse.emf.mwe2.language/src-gen/org/eclipse/emf/mwe2/language/services/Mwe2GrammarAccess.java
- plugins/org.eclipse.emf.mwe2.language/src-gen/org/eclipse/emf/mwe2/language/validation/AbstractMwe2Validator.java
> regen mwe2

- plugins/pom.xml
> removePack200 plugins

- maven/org.eclipse.emf.mwe2.target/org.eclipse.emf.mwe2.target.target
> bootstrap against 2.26.0.M3

- maven/org.eclipse.emf.mwe2.target/org.eclipse.emf.mwe2.target.target
bootstrap against 2.26.0 release
> bootstrap against 2.26.0 release

- features/org.eclipse.emf.mwe.core-feature/feature.xml
- features/org.eclipse.emf.mwe2.launcher-feature/feature.xml
- maven/org.eclipse.emf.mwe2.repository/category.xml
- maven/org.eclipse.emf.mwe2.target/org.eclipse.emf.mwe2.target.target
clean up apache.commons.cli dependency
> clean up apache.commons.cli dependency

- maven/org.eclipse.emf.mwe2.parent/pom.xml
> bump cli version in maven

- maven/org.eclipse.emf.mwe2.parent/pom.xml
- maven/org.eclipse.emf.mwe2.target/org.eclipse.emf.mwe2.target.target
- plugins/org.eclipse.emf.mwe2.language.ui/META-INF/MANIFEST.MF
- plugins/org.eclipse.emf.mwe2.language/META-INF/MANIFEST.MF
- plugins/org.eclipse.emf.mwe2.launch/META-INF/MANIFEST.MF
- plugins/org.eclipse.emf.mwe2.launch/pom.xml
- plugins/org.eclipse.emf.mwe2.lib/META-INF/MANIFEST.MF
- plugins/org.eclipse.emf.mwe2.runtime/META-INF/MANIFEST.MF
[eclipse/xtext#2028] switch to reload4j
> [eclipse/xtext#2028] switch to reload4j

- plugins/org.eclipse.emf.mwe.core/src/org/eclipse/emf/mwe/core/WorkflowRunner.java
- plugins/org.eclipse.emf.mwe2.launch/src/org/eclipse/emf/mwe2/launch/runtime/Mwe2Launcher.java
> fix cli deprecations

- maven/org.eclipse.emf.mwe2.parent/.settings/org.eclipse.core.resources.prefs
- maven/org.eclipse.emf.mwe2.repository/.settings/org.eclipse.core.resources.prefs
- plugins/org.eclipse.emf.mwe2.launch.ui/.settings/org.eclipse.core.resources.prefs
- plugins/org.eclipse.emf.mwe2.launch/.settings/org.eclipse.core.resources.prefs
- plugins/org.eclipse.emf.mwe2.lib/.settings/org.eclipse.core.resources.prefs
added missing org.eclipse.xtext.testlanguages.ide/.settings/org.eclipse.core.resources.prefs
> added missing org.eclipse.xtext.testlanguages.ide/.settings/org.eclipse.core.resources.prefs

- maven/org.eclipse.emf.mwe2.target/org.eclipse.emf.mwe2.target.target
> switch to orbit 2022-06

- Jenkinsfile
- maven/org.eclipse.emf.mwe2.parent/pom.xml
[eclipse/xtext#2057] update to centos-8 agent
> [eclipse/xtext#2057] update to centos-8 agent

- releng/jenkins/update-composite-site.Jenkinsfile
> fix jenkins depr

- maven/org.eclipse.emf.mwe2.parent/pom.xml
bump maven-javadoc-plugin to 3.4.1
> bump maven-javadoc-plugin to 3.4.1

- plugins/org.eclipse.emf.mwe.activities/.project
- plugins/org.eclipse.emf.mwe.core/.project
- plugins/org.eclipse.emf.mwe.ui.simpleEditor/.project
- plugins/org.eclipse.emf.mwe.ui/.project
- plugins/org.eclipse.emf.mwe.utils/.project
- plugins/org.eclipse.emf.mwe2.language.ide/.project
- plugins/org.eclipse.emf.mwe2.language.ui/.project
- plugins/org.eclipse.emf.mwe2.language/.project
- plugins/org.eclipse.emf.mwe2.launch.ui/.project
- plugins/org.eclipse.emf.mwe2.launch/.project
- plugins/org.eclipse.emf.mwe2.lib/.project
- plugins/org.eclipse.emf.mwe2.runtime/.project
- tests/org.eclipse.emf.mwe.tests/.project
- tests/org.eclipse.emf.mwe2.language.tests/.project
> remove api analysis

- maven/org.eclipse.emf.mwe2.parent/pom.xml
[#227] dont use explicit signing algos
> [#227] dont use explicit signing algos

- maven/org.eclipse.emf.mwe2.target/org.eclipse.emf.mwe2.target.target
[eclipse/xtext#2112] Fix Orbit signing problem
> [eclipse/xtext#2112] Fix Orbit signing problem

- maven/org.eclipse.emf.mwe2.target/org.eclipse.emf.mwe2.target.target
[eclipse/xtext#2112] switch back to orbit 2022-12
> [eclipse/xtext#2112] switch back to orbit 2022-12

- features/org.eclipse.emf.mwe2.language.sdk-feature/feature.xml
- features/org.eclipse.emf.mwe2.launcher-feature/feature.xml
- maven/org.eclipse.emf.mwe2.target/org.eclipse.emf.mwe2.target.target
- plugins/org.eclipse.emf.mwe2.language/META-INF/MANIFEST.MF
> bootstrap against Xtext 2.29

- tests/org.eclipse.emf.mwe.tests/src/org/eclipse/emf/mwe/core/ant/NotReallyAbstractWorkflowAntTaskTest.java
- tests/org.eclipse.emf.mwe.tests/src/org/eclipse/emf/mwe/tests/util/FileCopyTest.java
replace File.createTempFile with Files.createTempFile.toFile
> replace File.createTempFile with Files.createTempFile.toFile

- maven/org.eclipse.emf.mwe2.target/org.eclipse.emf.mwe2.target.target
bootstrap against 2.29 release
> bootstrap against 2.29 release

- maven/org.eclipse.emf.mwe2.parent/pom.xml
- maven/org.eclipse.emf.mwe2.target/org.eclipse.emf.mwe2.target.target
- plugins/org.eclipse.emf.mwe2.language.ui/META-INF/MANIFEST.MF
- plugins/org.eclipse.emf.mwe2.language/META-INF/MANIFEST.MF
- plugins/org.eclipse.emf.mwe2.launch/META-INF/MANIFEST.MF
- plugins/org.eclipse.emf.mwe2.lib/META-INF/MANIFEST.MF
- plugins/org.eclipse.emf.mwe2.runtime/META-INF/MANIFEST.MF
> bump reload4j

- plugins/org.eclipse.emf.mwe2.language.ide/src-gen/org/eclipse/emf/mwe2/language/ide/AbstractMwe2IdeModule.java
- plugins/org.eclipse.emf.mwe2.language.ide/src-gen/org/eclipse/emf/mwe2/language/ide/contentassist/antlr/Mwe2Parser.java
- plugins/org.eclipse.emf.mwe2.language.ide/src-gen/org/eclipse/emf/mwe2/language/ide/contentassist/antlr/PartialMwe2ContentAssistParser.java
- plugins/org.eclipse.emf.mwe2.language.ide/src-gen/org/eclipse/emf/mwe2/language/ide/contentassist/antlr/internal/InternalMwe2Parser.g
- plugins/org.eclipse.emf.mwe2.language.ide/src-gen/org/eclipse/emf/mwe2/language/ide/contentassist/antlr/internal/InternalMwe2Parser.java
- plugins/org.eclipse.emf.mwe2.language.ide/src-gen/org/eclipse/emf/mwe2/language/ide/contentassist/antlr/lexer/InternalMwe2Lexer.g
- plugins/org.eclipse.emf.mwe2.language.ide/src-gen/org/eclipse/emf/mwe2/language/ide/contentassist/antlr/lexer/InternalMwe2Lexer.java
- plugins/org.eclipse.emf.mwe2.language.ui/src-gen/org/eclipse/emf/mwe2/language/ui/AbstractMwe2UiModule.java
- plugins/org.eclipse.emf.mwe2.language.ui/src-gen/org/eclipse/emf/mwe2/language/ui/Mwe2ExecutableExtensionFactory.java
- plugins/org.eclipse.emf.mwe2.language.ui/src-gen/org/eclipse/emf/mwe2/language/ui/contentassist/AbstractMwe2ProposalProvider.java
- plugins/org.eclipse.emf.mwe2.language.ui/src-gen/org/eclipse/emf/mwe2/language/ui/internal/LanguageActivator.java
- plugins/org.eclipse.emf.mwe2.language/emf-gen/org/eclipse/emf/mwe2/language/mwe2/impl/Mwe2PackageImpl.java
- plugins/org.eclipse.emf.mwe2.language/src-gen/org/eclipse/emf/mwe2/language/AbstractMwe2RuntimeModule.java
- plugins/org.eclipse.emf.mwe2.language/src-gen/org/eclipse/emf/mwe2/language/Mwe2StandaloneSetupGenerated.java
- plugins/org.eclipse.emf.mwe2.language/src-gen/org/eclipse/emf/mwe2/language/parser/antlr/Mwe2AntlrTokenFileProvider.java
- plugins/org.eclipse.emf.mwe2.language/src-gen/org/eclipse/emf/mwe2/language/parser/antlr/Mwe2Parser.java
- plugins/org.eclipse.emf.mwe2.language/src-gen/org/eclipse/emf/mwe2/language/parser/antlr/internal/InternalMwe2Parser.g
- plugins/org.eclipse.emf.mwe2.language/src-gen/org/eclipse/emf/mwe2/language/parser/antlr/internal/InternalMwe2Parser.java
- plugins/org.eclipse.emf.mwe2.language/src-gen/org/eclipse/emf/mwe2/language/parser/antlr/lexer/InternalMwe2Lexer.g
- plugins/org.eclipse.emf.mwe2.language/src-gen/org/eclipse/emf/mwe2/language/parser/antlr/lexer/InternalMwe2Lexer.java
- plugins/org.eclipse.emf.mwe2.language/src-gen/org/eclipse/emf/mwe2/language/scoping/AbstractMwe2ScopeProvider.java
- plugins/org.eclipse.emf.mwe2.language/src-gen/org/eclipse/emf/mwe2/language/serializer/AbstractMwe2SemanticSequencer.java
- plugins/org.eclipse.emf.mwe2.language/src-gen/org/eclipse/emf/mwe2/language/serializer/AbstractMwe2SyntacticSequencer.java
- plugins/org.eclipse.emf.mwe2.language/src-gen/org/eclipse/emf/mwe2/language/services/Mwe2GrammarAccess.java
- plugins/org.eclipse.emf.mwe2.language/src-gen/org/eclipse/emf/mwe2/language/validation/AbstractMwe2Validator.java
- tests/org.eclipse.emf.mwe2.language.tests/src-gen/org/eclipse/emf/mwe2/language/tests/Mwe2InjectorProvider.java
- tests/org.eclipse.emf.mwe2.language.tests/src-gen/org/eclipse/emf/mwe2/language/ui/tests/Mwe2UiInjectorProvider.java
> regen mwe2 for 2023

- maven/org.eclipse.emf.mwe2.parent/pom.xml
> bump eclipse-jarsigner-plugin

- plugins/org.eclipse.emf.mwe2.language/generator/org/eclipse/emf/mwe2/language/GenerateMwe2.java
- plugins/org.eclipse.emf.mwe2.language/src/org/eclipse/emf/mwe2/language/Mwe2RuntimeModule.java
- plugins/org.eclipse.emf.mwe2.language/src/org/eclipse/emf/mwe2/language/factory/Mwe2ExecutionEngine.java
- plugins/org.eclipse.emf.mwe2.language/src/org/eclipse/emf/mwe2/language/factory/SettingProviderImpl.java
- plugins/org.eclipse.emf.mwe2.language/src/org/eclipse/emf/mwe2/language/validation/Mwe2Validator.java
- plugins/org.eclipse.emf.mwe2.language/src/org/eclipse/emf/mwe2/language/validation/MweRawSuperTypes.java
> fix some warnings

- Jenkinsfile
- README.md
- set_version.sh
add support for building m0 milestone
> add support for building m0 milestone

- features/org.eclipse.emf.mwe2.language.sdk-feature/feature.xml
- features/org.eclipse.emf.mwe2.launcher-feature/feature.xml
- features/org.eclipse.emf.mwe2.runtime.sdk-feature/feature.xml
- maven/org.eclipse.emf.mwe2.parent/pom.xml
- maven/org.eclipse.emf.mwe2.repository/category.xml
- maven/org.eclipse.emf.mwe2.target/org.eclipse.emf.mwe2.target.target
- plugins/org.eclipse.emf.mwe2.language.ui/META-INF/MANIFEST.MF
- plugins/org.eclipse.emf.mwe2.language/META-INF/MANIFEST.MF
- plugins/org.eclipse.emf.mwe2.lib/META-INF/MANIFEST.MF
- plugins/org.eclipse.emf.mwe2.runtime/META-INF/MANIFEST.MF
- tests/org.eclipse.emf.mwe2.language.tests/META-INF/MANIFEST.MF
[#251] update to Xtext 2.32.0.M0
> [#251] update to Xtext 2.32.0.M0

- features/org.eclipse.emf.mwe.core-feature/feature.xml
- features/org.eclipse.emf.mwe2.launcher-feature/feature.xml
- maven/org.eclipse.emf.mwe2.parent/pom.xml
- maven/org.eclipse.emf.mwe2.repository/category.xml
- maven/org.eclipse.emf.mwe2.target/org.eclipse.emf.mwe2.target.target
> [#256] update to cli 1.5

- features/org.eclipse.emf.mwe2.launcher-feature/feature.xml
- features/org.eclipse.emf.mwe2.runtime.sdk-feature/feature.xml
- maven/org.eclipse.emf.mwe2.parent/pom.xml
- maven/org.eclipse.emf.mwe2.repository/category.xml
- maven/org.eclipse.emf.mwe2.target/org.eclipse.emf.mwe2.target.target
- plugins/org.eclipse.emf.mwe2.language.ui/META-INF/MANIFEST.MF
- plugins/org.eclipse.emf.mwe2.lib/META-INF/MANIFEST.MF
[eclipse/xtext#2726] update to guava 32.1
> [eclipse/xtext#2726] update to guava 32.1

- features/org.eclipse.emf.mwe2.launcher-feature/feature.xml
- features/org.eclipse.emf.mwe2.runtime.sdk-feature/feature.xml
- maven/org.eclipse.emf.mwe2.parent/pom.xml
- maven/org.eclipse.emf.mwe2.repository/category.xml
- maven/org.eclipse.emf.mwe2.target/org.eclipse.emf.mwe2.target.target
- plugins/org.eclipse.emf.mwe2.language.ui/META-INF/MANIFEST.MF
- plugins/org.eclipse.emf.mwe2.lib/META-INF/MANIFEST.MF
> update to guava 32.1.1

- maven/org.eclipse.emf.mwe2.target/org.eclipse.emf.mwe2.target.target
[#254] bootstrap against Xtext 2.32 release
> [#254] bootstrap against Xtext 2.32 release

- Jenkinsfile
- features/org.eclipse.emf.mwe.core-feature/pom.xml
- features/org.eclipse.emf.mwe.doc-feature/pom.xml
- features/org.eclipse.emf.mwe.sdk-feature/pom.xml
- features/org.eclipse.emf.mwe2.language.sdk-feature/pom.xml
- features/org.eclipse.emf.mwe2.runtime.sdk-feature/pom.xml
- features/pom.xml
dont use extras feature source plugin
update to maven 3.9.1
> dont use extras feature source plugin

- maven/org.eclipse.emf.mwe2.parent/pom.xml
- maven/org.eclipse.emf.mwe2.repository/category.xml
- maven/org.eclipse.emf.mwe2.target/org.eclipse.emf.mwe2.target.nightly/org.eclipse.emf.mwe2.target.nightly.target
- maven/org.eclipse.emf.mwe2.target/org.eclipse.emf.mwe2.target/org.eclipse.emf.mwe2.target.target
> fix broken deps in orbit

- tests/org.eclipse.emf.mwe2.language.tests/src/org/eclipse/emf/mwe2/language/tests/contentassist/ContentAssistTest.java
[#270] ignore flaky test as no time to investigate in Xtext or JDT
> [#270] ignore flaky test as no time to investigate in Xtext or JDT

- Jenkinsfile
> Fix Latest build

- NOTICE.md
- maven/org.eclipse.emf.mwe2.parent/pom.xml
- maven/org.eclipse.emf.mwe2.repository/category.xml
- maven/org.eclipse.emf.mwe2.target/org.eclipse.emf.mwe2.target.nightly/org.eclipse.emf.mwe2.target.nightly.target
- maven/org.eclipse.emf.mwe2.target/org.eclipse.emf.mwe2.target/org.eclipse.emf.mwe2.target.target
- plugins/org.eclipse.emf.mwe.doc/build-docbook.xml
- tests/org.eclipse.emf.mwe.tests/META-INF/MANIFEST.MF
@cdietrich this is mostly the commit on your branch with the following additions
- Use Import-package in org.eclipse.emf.mwe.tests
- Update `build-docbook.xml` (have not tested it).
- Generalize License entry in NOTICE.md (i.e. use Project name instead of BSN).
> Migrate to latest commons-logging (currently 1.3.3)

- releng/MWE.setup
The other changes are automatically applied by the Oomph Setup Editor
> Remove activation of gerrit-createchangeid from Oomph setup

- Jenkinsfile
@cdietrich can you please `Replay` this change to test its effect?
> [Build] Clean-up Jenkinsfile and remove unnecessary elements

- features/org.eclipse.emf.mwe.core-feature/feature.xml
- features/org.eclipse.emf.mwe2.launcher-feature/feature.xml
- features/org.eclipse.emf.mwe2.runtime.sdk-feature/feature.xml
- maven/org.eclipse.emf.mwe2.parent/pom.xml
- maven/org.eclipse.emf.mwe2.repository/category.xml
- maven/org.eclipse.emf.mwe2.target/org.eclipse.emf.mwe2.target.nightly/org.eclipse.emf.mwe2.target.nightly.target
- maven/org.eclipse.emf.mwe2.target/org.eclipse.emf.mwe2.target/org.eclipse.emf.mwe2.target.target
- plugins/org.eclipse.emf.mwe2.language.ui/META-INF/MANIFEST.MF
- plugins/org.eclipse.emf.mwe2.lib/META-INF/MANIFEST.MF
https://github.com/eclipse/xtext/issues/3161
> Update to guava 30.3.0.jre

- features/org.eclipse.emf.mwe.core-feature/feature.xml
- features/org.eclipse.emf.mwe2.launcher-feature/feature.xml
- plugins/org.eclipse.emf.mwe.core/META-INF/MANIFEST.MF
- plugins/org.eclipse.emf.mwe.utils/META-INF/MANIFEST.MF
- tests/org.eclipse.emf.mwe.tests/META-INF/MANIFEST.MF
Closes #310 
I increased the minimum version and added the dependency in the hopefully proper features.
> Add org.apache.commons.commons-logging as dep in features

- Jenkinsfile
This also fixes the need to activate 'tycho.resolver.classic'.
Fixes https://github.com/eclipse/mwe/issues/277
> [Build] Remove unused javadoc aggregation jar
